<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css" media="all"/>
<title></title>
</head>
<body>
<h1>PETITES ANNONCES</h1>
<form method="get" action="modification.php?key=<?= intval($annonce['id']) ?>" >
    <article>
        <input type="text" value ="<?= htmlspecialchars($annonce['titre']) ?>" name="titre">
        <input type="text" value ="<?= htmlspecialchars($annonce['descriptif']) ?>" name="descriptif">
        <input type="text" value ="<?= htmlspecialchars($annonce['prix']) ?>" name="prix">
    </article>
    <input type="submit"  value="Valider">
</form>
</body>
</html> 


