<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css" media="all"/>
<title></title>
</head>
<body>
<h1>PETITES ANNONCES</h1>
<?php foreach($annonces as $key => $annonce): ?>
 <article>
    <h3><?= htmlspecialchars($annonce['titre']) ?></h3>
    <p><?= htmlspecialchars($annonce['descriptif']) ?></p>
    <span><?= htmlspecialchars($annonce['prix']) ?></span>
    </article>
<?php endforeach ?>
</body>
</html> 

 