<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css" media="all"/>
<title></title>
</head>
<body>
<h1>PETITES ANNONCES</h1>
<div class="topnav">
<a class="active" href="#home">Annonces</a>
</div>   
<form method="POST" action="insertion.php" >
<fieldset>
    <legend>Rédacteur</legend>
    <input type="text" name="titre" placeholder="Titre">
    <textarea name="descriptif" rows="10" cols="30" placeholder="Rédiger votre annonce"></textarea>
    <input type="text" name="prix" placeholder="Prix">
    <input type="text" id="idutilisateur" placeholder="Pseudo">
</fieldset>
<input type="submit" name="nom" value="Valider">
</form>
<form action="insertion.php" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="<?= MAX_FILE_SIZE ?>">
        <input type="file" name="images[]" multiple accept="<?= implode(',', MIME_TYPES_ACCEPTED) ?>">
        <button type="submit">Envoyer</button>
</form>

</body>
</html>
