<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css" media="all"/>
<title></title>
</head>
<body>
<h1><font face="Arial, geneva">
    <b>PETITES ANNONCES</b>
    </font>
</h1>
<div class="topnav">
<a class="active" href="#home">Formulaire</a>
</div>   
<form method="post" action="insertion.php" >
<fieldset>
    <legend>Rédacteur</legend>
    <input type="text" name="titre" placeholder="Titre">
    <input type="text" id="idredacteur" placeholder="Pseudo">
</fieldset>
    <textarea name="corps" rows="10" cols="30" placeholder="Rédiger votre article"></textarea>
    <input type="submit" name="nom" value="Valider">
</form>
</body>
</html>
</body>
</html>