<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css" media="all"/>
<title></title>
</head>
<body>
<h1><font face="Arial, geneva">
    <b>PETITES ANNONCES</b>
    </font>
</h1>
<nav>
    <a href="#" class="active">Déconnexion</a>
    <a href="#">Annonces parues</a>
    <a href="#">Créer votre annonce</a>
</nav>
</body>
</html>
</body>
</html>

